services:
  # app:
  #   build: .
  #   links:
  #     - db
  #   ports:
  #     - "5000:5000"
  db:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=scrapnet

    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/:ro